
type Theme = {
    name: ThemeNames,
    bg: string,
    bgAlt: string,
    main: string,
    caret: string,
    error: string,
    sub: string,
    text: string,
    font: string,
    fontSize: string,
    uiFont: string,
    uiFontSize: string,
    transitionSpeed: string,
    tabbarScrollbarSize: string,
    tabbarHeight: string,
    tabHeight: string,
    tabRadius: string,
    tabGaps: string,
    editorScrollbarSize: string,
}

export type ThemeNames = "One Dark" | "Rose Pine Dawn"
export const themes: Theme[] = [
     {
        name: "One Dark",
        bg: "#2f343f",
        bgAlt: "#262b34",
        main: "#61afef",
        caret: "#61afef",
        error: "#e06c75",
        sub: "#eceff4",
        text: "#98c379",
        font: `"Consolas", monospace`,
        fontSize: "14px",
        uiFont: `"Segoe UI", sans-serif`,
        uiFontSize: "16px",
        transitionSpeed: "200ms",
        tabbarScrollbarSize: "0.3rem",
        tabbarHeight: "60px",
        tabHeight: "40px",
        tabRadius: "12px",
        tabGaps: "6px",
        editorScrollbarSize: "0.3rem",
    },
    {
        name: "Rose Pine Dawn",
        bg: "#fffaf3",
        bgAlt: "#f0e9df",
        main: "#56949f",
        caret: "#ea9d34",
        error: "#b4637a",
        sub: "#c4a7e7",
        text: "#286983",
        font: `"Consolas", monospace`,
        fontSize: "14px",
        uiFont: `"Segoe UI", sans-serif`,
        uiFontSize: "16px",
        transitionSpeed: "200ms",
        tabbarScrollbarSize: "0.3rem",
        tabbarHeight: "60px",
        tabHeight: "40px",
        tabRadius: "12px",
        tabGaps: "6px",
        editorScrollbarSize: "0.3rem",
    },
]